image: lbaf23/ptm-leaderboard-api:1.0.0

stages:
  - deploy

deploy:
  stage: deploy
  when: manual
  variables:
    CI_DEBUG_TRACE: "true"
  script:
    - bash api/up.sh
  tags:
    - ptm
  only:
    - master
