apiVersion: v1
kind: Secret
metadata:
  name: ptm-secret
  namespace: ptm
type: Opaque
data:
  dbhost: ''
  dbuser: ''
  dbpassword: ''
  dbport: ''
  dbname: ''

  casdoorendpoint: ''
  casdoorclientid: ''
  casdoorclientsecret: ''
  casdoororganization: ''
  applicationname: ''

  natsurl: ''

  region: ''
  accesskeyid: ''
  accesskeysecret: ''
  rolearn: ''
  rolesessionname: ''
  bucket: ''

  localserver: ''
