version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080
functions:
  leaderboard:
    lang: dockerfile
    handler: ./web
    image: lbaf23/ptm-leaderboard-web:1.0.0
    labels:
      com.openfaas.scale.zero: false
  api:
    lang: dockerfile
    handler: ./api
    image: lbaf23/ptm-leaderboard-api:1.0.0
    build_args:
      GO111MODULE: on
    environment:
      RunMode: release
  attack:
    lang: python3
    handler: ./attack
    image: lbaf23/ptm-leaderboard-attack:1.0.0
    environment:
      run_mode: release

