version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:31112
functions:
  leaderboard:
    lang: dockerfile
    handler: ./web
    image: lbaf23/ptm-leaderboard-web:latest
    labels:
      com.openfaas.scale.zero: false
  server:
    lang: dockerfile
    handler: ./server
    image: lbaf23/ptm-leaderboard-server:latest
    build_args:
      GO111MODULE: on
    environment:
      run_mode: release
      postgres_db: ptm_leaderboard_db
      postgres_port: 5432
      postgres_host: postgresql.default.svc.cluster.local
      postgres_user: postgres
      postgres_sslmode: disable
    secrets:
      - ptm-leaderboard-db-password

