version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:31112
functions:
  leaderboard:
    lang: dockerfile
    handler: ./web
    image: lbaf23/ptm-leaderboard-web:1.0.0
    labels:
      com.openfaas.scale.zero: false
  api:
    lang: dockerfile
    handler: ./api
    image: lbaf23/ptm-leaderboard-api:1.0.0
    build_args:
      GO111MODULE: on
    environment:
      run_mode: release
      postgres_db: ptm_leaderboard_db
      postgres_port: 5432
      postgres_host: postgresql.default.svc.cluster.local
      postgres_user: postgres
      postgres_sslmode: disable
    secrets:
      - ptm-leaderboard-db-password
  attack:
    lang: python3
    handler: ./input
    image: lbaf23/ptm-leaderboard-input:1.0.0

