apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ptm
  labels:
    app: api
    component: api
spec:
  type: NodePort
  ports:
    - name: http
      port: 12002
      targetPort: 12002
      protocol: TCP
      nodePort: 30002
  selector:
    app: api
