apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: ptm
  labels:
    app: nats
    component: nats
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 4222
      targetPort: 4222
      protocol: TCP
      nodePort: 30005
  selector:
    app: nats
