apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: ptm
  labels:
    app: web
    component: web
spec:
  type: NodePort
  ports:
    - name: http
      port: 12001
      targetPort: 12001
      protocol: TCP
      nodePort: 30001
  selector:
    app: web
