apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ptm
  labels:
    app: api
    component: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: lbaf23/ptm-leaderboard-api:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
              cpu: "10m"
          ports:
            - containerPort: 12002
          livenessProbe:
            httpGet:
              path: /tasklist/english/
              port: 12002
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /tasklist/english/
              port: 12002
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          

          env:
            - name: RunMode
              value: release
              
            - name: DBHost
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: dbhost
            - name: DBUser
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: dbuser
            - name: DBPassword
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: dbpassword
            - name: DBPort
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: dbport
            - name: DBName
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: dbname

            - name: CasdoorEndpoint
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: casdoorendpoint
            - name: CasdoorClientId
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: casdoorclientid
            - name: CasdoorClientSecret
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: casdoorclientsecret
            - name: CasdoorOrganization
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: casdoororganization
            - name: ApplicationName
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: applicationname
            - name: NATSURL
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: natsurl
