apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ptm
  labels:
    app: api
    component: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: lbaf23/ptm-leaderboard-api:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "10Mi"
            cpu: "50m"
        ports:
        - containerPort: 12002
