apiVersion: apps/v1
kind: Deployment
metadata:
  name: attack
  namespace: ptm
  labels:
    app: attack
    component: attack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attack
  template:
    metadata:
      labels:
        app: attack
    spec:
      containers:
      - name: attack
        image: lbaf23/ptm-leaderboard-attack:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
            nvidia.com/gpu: "1"
