apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: ptm
  labels:
    app: auth
    component: auth
spec:
  type: NodePort
  ports:
    - name: http
      port: 12003
      targetPort: 12003
      protocol: TCP
      nodePort: 30003
  selector:
    app: auth
