apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: ptm
  labels:
    app: auth
    component: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: lbaf23/ptm-leaderboard-auth:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          ports:
            - containerPort: 12003
          volumeMounts:
            - name: files
              mountPath: /files
      volumes:
        - name: files
          hostPath:
            path: /home/lbaf23/ptm/files
            type: DirectoryOrCreate
