apiVersion: v1
kind: Pod
metadata:
  name: auth
  namespace: ptm
  labels:
    k8s-app: auth
spec:
  containers:
  - name: auth
    image: lbaf23/ptm-leaderboard-auth:1.0.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
    ports:
    - containerPort: 12003
