apiVersion: v1
kind: Service
metadata:
  name: file
  namespace: ptm
  labels:
    app: file
    component: file
spec:
  type: NodePort
  ports:
    - name: http
      port: 12006
      targetPort: 12006
      protocol: TCP
      nodePort: 30006
  selector:
    app: file
