apiVersion: apps/v1
kind: Deployment
metadata:
  name: file
  namespace: ptm
  labels:
    app: file
    component: file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file
  template:
    metadata:
      labels:
        app: file
    spec:
      containers:
        - name: file
          image: lbaf23/ptm-leaderboard-file:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 12006
          volumeMounts:
            - name: files
              mountPath: /files
          env:
            - name: RunMode
              value: release
            
            - name: LocalServer
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: localserver
            
            - name: Region
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: region
            - name: AccessKeyId
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: accesskeyid
            - name: AccessKeySecret
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: accesskeysecret
            - name: RoleArn
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: rolearn
            - name: RoleSessionName
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: rolesessionname
            - name: Bucket
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: bucket

            - name: CasdoorEndpoint
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: casdoorendpoint
            - name: CasdoorClientId
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: casdoorclientid
            - name: CasdoorClientSecret
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: casdoorclientsecret
            - name: CasdoorOrganization
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: casdoororganization
            - name: ApplicationName
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: applicationname
      volumes:
        - name: files
          hostPath:
            path: /home/lbaf23/ptm/files
            type: DirectoryOrCreate
