apiVersion: v1
kind: Pod
metadata:
  name: nats
  namespace: ptm
  labels:
    k8s-app: nats
spec:
  containers:
  - name: nats
    image: nats
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 1024mb
    ports:
    - containerPort: 4222
