apiVersion: apps/v1
kind: Deployment
metadata:
  name: send
  namespace: ptm
  labels:
    app: send
    component: send
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send
  template:
    metadata:
      labels:
        app: send
    spec:
      containers:
        - name: send
          image: lbaf23/ptm-leaderboard-send:1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 12007
          env:
            - name: RunMode
              value: release
              
            - name: NATSURL
              valueFrom:
                secretKeyRef:
                  name: ptm-secret
                  key: natsurl
