apiVersion: v1
kind: Service
metadata:
  name: send
  namespace: ptm
  labels:
    app: send
    component: send
spec:
  type: NodePort
  ports:
    - name: http
      port: 12007
      targetPort: 12007
      protocol: TCP
      nodePort: 30007
  selector:
    app: send
