apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ptm
  labels:
    app: web
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: lbaf23/ptm-leaderboard-web:1.0.3
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "100Mi"
            cpu: "300m"
        ports:
          - containerPort: 12001
        env:
          - name: PUBLIC_URL
            value: "/"
          - name: REACT_APP_OSS
            value: "off"
          - name: REACT_APP_OSS_REGION
            valueFrom:
              secretKeyRef:
                name: ptm-secret
                key: region
          - name: REACT_APP_BASE_URL
            valueFrom:
              secretKeyRef:
                name: ptm-secret
                key: baseurl
          - name: REACT_APP_FILE_URL
            valueFrom:
              secretKeyRef:
                name: ptm-secret
                key: fileurl
          - name: REACT_APP_CASDOOR_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: ptm-secret
                key: casdoorendpoint
          - name: REACT_APP_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: ptm-secret
                key: casdoorclientid
          - name: REACT_APP_APP_NAME
            valueFrom:
              secretKeyRef:
                name: ptm-secret
                key: applicationname
          - name: REACT_APP_CASDOOR_ORGANIZATION
            valueFrom:
              secretKeyRef:
                name: ptm-secret
                key: casdoororganization
